name: setup-tests
version: 1.0.0.0

dependencies:
  - base

executables:
  setup-tests:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
    dependencies:
      - aeson
      - directory
      - lens
      - lens-aeson
      - yaml
